### ISSUE TITLE
Refactoring des endpoints

### ISSUE THREAD

**Issue by Callidon** [Callidon/GalacticHorse#10]
Uniformiser les endpoints et vérifier qu'ils vérifient bien les principes REST

**Comment by Giraudux** [comment]
Merge Search and Ontology endpoints in Search endpoint.
Todo: add link relation
(Todo: split DataBean in RequestBean/ResponseBean)

**Comment by Giraudux** [comment]
- mapping and link relation (HATEOAS) updated
- check JSON-LD on insert (check properties and objects)
- request on host name is ready
