### ISSUE TITLE
Authentification

### ISSUE THREAD

**Issue by Callidon** [Callidon/GalacticHorse#11]
Ajouter et gérer l'authentification dans l'extension et au niveau des endpoints

**Comment by Callidon** [comment]
**MAJ** :
- Activation des APIs requises (Contacts et Google+) côté App Engine
- Installation de satellizer côté extension pour gérer l'OAuth2
- Clé d'authentification générée pour l'application

**TODO** : mettre en place le protocole complet côté extension

**Comment by Callidon** [comment]
**MAJ :** Possibilité de se connecter/déconnecter de l'extension

**TODO :** Vérifier que la cache où est stocké le token est bien vidé au moment de la déconnexion

**Comment by Giraudux** [comment]
Endpoint authentication OK

**Comment by Callidon** [comment]
A priori, tout est bon côté extension. Le token est conservé via le compte Google, donc pour tester des connexions avec des comptes différents, il faut passer par la navigation privée.

**Comment by Callidon** [comment]
Mauvais header corrigé côté extension, tout fonctionne au poil
