### ISSUE TITLE
Croisement des données CustomSearch/Datastore

### ISSUE THREAD

**Issue by Callidon** [Callidon/GalacticHorse#6]
**Prérequis** : #5 
**Tâche**
Croiser les données récupérée depuis la CustomSearch avec celle du Datastore pour récupérer nos données enrichies

**Comment by ninouille64210** [comment]
T'as trouvé ?

**Comment by Callidon** [comment]
Yep, ça s'est fait tranquille côté Angular. On fait ça dans le service SearchMerge (https://github.com/Callidon/GalacticHorse/blob/master/galactichorse/src/main/webapp/js/services/SearchMerge.js)
